sudo: required
dist: trusty
language: node_js

matrix:
  include:
    - os: osx
      node_js: 6
    - os: linux
      node_js: 6
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

branches:
  only:
    - master

cache:
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.electron
    - $HOME/.cache

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
      - xvfb
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm
      - bsdtar


before_script:
  - npm prune

script: ./script/travis-build.sh
